version: 1
formatters:
    simple:
        format: "%(asctime)s - %(module)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: simple
        filename: log/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: simple
        filename: log/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    adlink_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: simple
        filename: log/adlink.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    masbot.device.motor:
        level: DEBUG
        handlers: [console, info_file_handler]
        propagate: false

    masbot.device.motion.adlink:
        level: DEBUG
        handlers: [console, adlink_file_handler]
        propagate: false

    masbot.device.motion.adlink_fake:
        level: DEBUG
        handlers: [console, adlink_file_handler]
        propagate: false

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler, adlink_file_handler]
